version: "3"

networks:
  todo:

services:
  mysql:
    image: coney/mysql:5
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    networks:
      todo:
        aliases:
          - mysql
    ports:
      - "3306:3306"
  config-server:
    image: yangliumingtest/config-server:1
    networks:
      todo:
        aliases:
          - config-server
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  zuul:
    image: yangliumingtest/zuul:1
    depends_on:
      - config-server
    networks:
      todo:
        aliases:
          - zuul
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  user-service:
    image: yangliumingtest/user-service:1
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
    depends_on:
      - mysql
      - config-server
      - zuul
    networks:
      todo:
        aliases:
          - user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  todo-service:
    image: yangliumingtest/todo-service:1
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
    depends_on:
      - mysql
      - config-server
      - zuul
    networks:
      todo:
        aliases:
          - todo-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default




